src/components/DsfrBreadcrumb/DsfrBreadcrumb.stories.js
src/components/DsfrButton/DsfrButton.stories.js
src/components/DsfrCard/DsfrCard.stories.js
src/components/DsfrCheckBox/DsfrCheckbox.stories.js
src/components/DsfrCheckBox/DsfrCheckboxSet.stories.js
src/components/DsfrInput/DsfrInput.stories.js
src/components/DsfrRadioButton/DsfrRadioButton.stories.js
src/components/DsfrRadioButton/DsfrRadioButtonSet.stories.js
src/components/DsfrSearchBar/DsfrSearchBar.stories.js
src/stories/docs/dev.stories.mdx
src/stories/docs/guide.stories.mdx
src/stories/docs/intro.stories.mdx

Utilise des noms en français dans le Storybook

docs: :memo: Utilise des noms en français pour les composants

---

src/components/DsfrTabs/DsfrTabContent.vue
src/components/DsfrTabs/DsfrTabItem.vue
src/components/DsfrTabs/DsfrTabs.spec.js
src/components/DsfrTabs/DsfrTabs.stories.js
src/components/DsfrTabs/DsfrTabs.vue

- onglets opérationnels et responsive
- manque les animations

:sparkles: Implémente les onglets

---

package.json
release.config.js

- Ajoute un fichier de configuration release.config.js
- Ajoute un script "prepublishOnly" pour générer la bibliothèque

ci(releases): :green_heart: Configure semantic-release

---

README.md
src/stories/docs/guide.stories.mdx

Plus d'informations sur l'utilisation, avec des exemples, et un lien vers le storybook en-ligne

docs: :memo: Améliore la documentation du guide

---

src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue

oh-vue-icons est importé globalement

chore: :white_check_mark: Supprime l'import de oh-vue-icons

---

src/components/DsfrPagination/DsfrPagination.e2e.js
src/components/DsfrPagination/DsfrPagination.spec.js
src/components/DsfrPagination/DsfrPagination.stories.js
src/components/DsfrPagination/DsfrPagination.vue
src/components/DsfrPagination/pagination.main.css

Correction bugs navigation
Amélioration accessibilité
Ajout troncature au delà de 5 pages

Feat(#205) : DsfrPagination

---

src/components/DsfrCheckbox/DsfrCheckbox.stories.js
src/components/DsfrCheckbox/DsfrCheckbox.vue
src/components/DsfrRadioButton/DsfrRadioButton.vue

fix: 🐛 Prend en compte required pour checkbox et radio-button

---

src/components/DsfrMedia/DsfrPicture.stories.js
src/components/DsfrMedia/DsfrPicture.vue

feat: :sparkles: Ajout d'un slot pour les svg

---

rollup.config.js
src/components/DsfrAlert/DsfrAlert.vue
src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
src/components/DsfrButton/DsfrButton.vue
src/components/DsfrFollow/DsfrNewsLetter.vue
src/components/DsfrHeader/DsfrHeader.vue
src/components/DsfrModal/DsfrModal.vue
src/components/DsfrNavigation/DsfrNavigation.vue
src/components/DsfrNavigation/DsfrNavigationMenu.vue
src/components/DsfrSideMenu/DsfrSideMenu.vue
src/components/DsfrTabs/DsfrTabs.vue
src/components/DsfrToggleSwitch/DsfrToggleSwitch.vue
src/demo-app/App.vue
src/index.js

Pour l’instant, impossible d’utiliser le JS du DSFR dans nuxt

fix: :bug: Corrige le bug dans nuxt

---

src/components/DsfrFooter/DsfrFooter.vue

feat: :sparkles: Permet la personnalisation des liens obligatoires

---

src/components/DsfrAccordion/DsfrAccordion.stories.js
src/components/DsfrAccordion/DsfrAccordion.vue

Donner la possibilité de customiser le titre de l'accordéon
Fix: #298

feat([DsfrAccordion]): :sparkles: Customisation du titre

---

src/components/DsfrInput/DsfrInput.stories.js
src/components/DsfrInput/DsfrInput.vue

ajoute une étoile en route à la fin du label

feat: :sparkles: Ajoute la props required sur le composant DsfrInput

---

src/stories/fondamentaux/icones-officielles.stories.mdx
src/stories/fondamentaux/icones-personnalisees.stories.mdx

Ajoute une page pour les icônes officielles
et une pour les autres icônes

feat: :memo: Améliore la documentation pour l’utilisation d’icônes

---

src/components/DsfrAccordion/DsfrAccordion.vue

fix(DsfrAccordion): :bug: Ajout Type button sur accordéon

---

README.md
src/stories/docs/02-guide.stories.mdx

Désormais, la version 1.0.0 est sortie

docs: :memo: Supprime la mention beta

---

src/components/DsfrFieldset/DsfrFieldset.spec.js
src/components/DsfrFieldset/DsfrFieldset.vue

Ajoute aussi des tests pour legend-class et hint-class

fix(DsfrFieldset)): :bug: Utilise le contenu de la props hint-class

---

src/components/DsfrFooter/DsfrFooter.stories.js
src/components/DsfrFooter/DsfrFooter.vue
types/components/DsfrFooter/DsfrFooter.vue.d.ts

feat(DsfrFooter): :sparkles: Ajout de props qualifiant la licence

---

src/components/DsfrTabs/DsfrTabs.stories.js
src/components/DsfrTabs/DsfrTabs.vue
types/components/DsfrTabs/DsfrTabs.vue.d.ts

Dsfr tabs choix tab initial

---

src/components/DsfrModal/DsfrModal.vue

Implémentation du fix https://github.com/dnum-mi/vue-dsfr/issues/385 proposé par [maxbellec](https://github.com/maxbellec)

fix: Hide body overflow when modal is open

---

src/components/DsfrToggleSwitch/DsfrToggleSwitch.vue

Fix broken reference on DsfrToggleSwitch input label
Fix: #420

fix(DsfrToggleSwitch): :bug: aria-describedby broken reference

---

src/components/DsfrTable/DsfrTableHeader.vue

style: :wheelchair: Ajout du scope col aux headers des tableaux

---

.gitignore
src/components/DsfrModal/DsfrModal.stories.js
src/components/DsfrModal/DsfrModal.vue

Ajout de la possibilité de mettre une icône sur les titres des modales

feat: add icon to modal title

---

src/components/DsfrFileDownload/DsfrFileDownloadList.spec.js
src/components/DsfrFileDownload/DsfrFileDownloadList.stories.js
src/components/DsfrFileDownload/DsfrFileDownloadList.vue

Fix/add title prop to `DsfrFileDownloadList`

---

src/components/DsfrShare/DsfrShare.vue

fix(DsfrShare): Fixed share @click context issue by using methods

---

src/components/DsfrShare/DsfrShare.vue

fix: :bug: Lookup window et navigator depuis script (pas la template)

---

src/components/DsfrLanguageSelector/DsfrLanguageSelector.vue

fix: :bug: Afficher le code ISO de la langue courante sur le bouton

---

src/components/DsfrCheckbox/DsfrCheckbox.vue
src/components/DsfrCheckbox/DsfrCheckboxSet.vue
src/components/DsfrFileUpload/DsfrFileUpload.spec.js
src/components/DsfrFileUpload/DsfrFileUpload.vue
src/components/DsfrFollow/DsfrNewsLetter.vue
src/components/DsfrInput/DsfrInputGroup.vue
src/components/DsfrRadioButton/DsfrRadioButtonSet.vue

fix: Missing DSFR classes on InputGroup message dnum-mi/vue-dsfr#451

---

src/stories/docs/02-guide.stories.mdx

- Le projet de base Nuxt 3 est maintenant hébergé sur Codesandbox

docs: :memo: Modification du projet de base Nuxt 3

---

src/components/DsfrFooter/DsfrFooter.vue
src/components/DsfrFooter/DsfrFooterLinkList.vue
src/components/DsfrFooter/DsfrFooterPartners.vue
src/components/DsfrTile/DsfrTile.vue
src/demo-app/views/AppHome.vue

fix: :bug: Utilise target blank pour les liens externes

---

src/components/DsfrHeader/DsfrHeader.stories.js
src/components/DsfrHeader/DsfrHeader.vue
src/components/DsfrHeader/DsfrHeaderMenuLink.vue
src/components/DsfrHeader/DsfrHeaderMenuLinks.vue

[DsfrHeader] Fix quick link : #483 #484 #486

---

src/components/DsfrSkipLinks/DsfrSkipLinks.stories.js
src/components/DsfrSkipLinks/DsfrSkipLinks.vue

Implémentation du scroll manuel pour l'utilisation des liens d'évitement
Fix: #481

fix([DsfrSkipLink]): :bug: Les liens d'évitement ne peuvent pas fonctionner

---

src/components/DsfrHeader/DsfrHeader.vue

https://github.com/dnum-mi/vue-dsfr/issues/486

fix: :bug: Ajout balise nav pour les liens (fix RGAA) + Ajout icone oubliée de recherche du header en format mobile

---

.vscode/settings.json
src/components/DsfrFileUpload/DsfrFileUpload.vue
src/components/DsfrFooter/DsfrFooter.vue
src/components/DsfrRadioButton/DsfrRadioButton.vue

Quelques correctifs de validité html

fix(Validité HTML): :bug: Correction validité HTML

---

src/components/DsfrRadioButton/DsfrRadioButton.stories.js
src/components/DsfrRadioButton/DsfrRadioButton.vue
src/components/DsfrRadioButton/DsfrRadioButtonSet.stories.js
src/components/DsfrRadioButton/DsfrRadioButtonSet.vue

- Add missing `small` prop to use `fr-radio-group--sm` on DsfrRadioButton

fix(DsfrRadioButton): Add missing `small` prop on DsfrRadioButton

---

src/components/DsfrFileDownload/DsfrFileDownload.spec.js
src/components/DsfrFileDownload/DsfrFileDownload.stories.js
src/components/DsfrFileDownload/DsfrFileDownload.vue
src/components/DsfrFileDownload/DsfrFileDownloadList.spec.js
src/components/DsfrFileDownload/DsfrFileDownloadList.stories.js
src/components/DsfrFileDownload/DsfrFileDownloadList.vue

feat: :sparkles: add download props for `DsfrFileDownload`

---

package.json

fix: :bug: corrige l’import pour webpack

---

src/components/DsfrHeader/DsfrHeaderMenuLink.vue
src/components/DsfrSearchBar/DsfrSearchBar.vue

fix(DsfrSearchbar): :bug: corrige le bug de la prop label-visible

---

src/components/DsfrTable/DsfrTable.vue

fix([DsfrTable]): :bug: Le tableau ne devrait pas être tronqué lorsque la pagination n'est pas activée

---

src/components/DsfrSkipLinks/DsfrSkipLinks.e2e.ts
src/components/DsfrSkipLinks/DsfrSkipLinks.stories.ts
src/components/DsfrSkipLinks/DsfrSkipLinks.vue

L'intérêt d'un lien d'évitement est de pouvoir arriver directement sur le contenu principal du site.
Il est donc primordiale de donner le focus à l'élément ciblé par le lien d'évitement.

feat(DsfrSkipLinks): ♿ Le contenu ciblé par le lien d'évitement prend le focus

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
commitlint.config.cjs
package-lock.json
package.json

Yorkie n'est plus maintenu et est de base un fork de husky
Voici une proposition de passage sur husky directement avec l'ajout de commitlint-conventional

ci(husky): remplacement yorkie par husky

---

README.md

Correction des liens KO dans le readme

fix(readme): ✏️ correction des liens vers le storybook

---

package-lock.json
package.json
src/components/DsfrSegmented/DsfrSegmented.spec.ts
src/components/DsfrSegmented/DsfrSegmented.stories.ts
src/components/DsfrSegmented/DsfrSegmented.types.ts
src/components/DsfrSegmented/DsfrSegmented.vue
src/components/DsfrSegmented/DsfrSegmentedSet.e2e.ts
src/components/DsfrSegmented/DsfrSegmentedSet.spec.ts
src/components/DsfrSegmented/DsfrSegmentedSet.stories.ts
src/components/DsfrSegmented/DsfrSegmentedSet.vue

https://main--ds-gouv.netlify.app/example/component/segmented/
fait partie de #679

feat: :sparkles: Nouveau composant Segmented (Contrôle Segmenté)

---

src/components/DsfrFollow/DsfrFollow.e2e.ts
src/components/DsfrFollow/DsfrFollow.stories.ts
src/components/DsfrFollow/DsfrFollow.types.ts
src/components/DsfrFollow/DsfrSocialNetworks.spec.ts
src/components/DsfrFollow/DsfrSocialNetworks.stories.ts
src/components/DsfrFollow/DsfrSocialNetworks.vue
src/components/DsfrShare/DsfrShare.spec.ts
src/components/DsfrShare/DsfrShare.stories.ts

feat: :boom: migration twitter-x DSFR v1.11.0

---

src/components/DsfrTable/DsfrTable.types.ts
src/components/DsfrTable/DsfrTable.vue

- permet que le tableau soit bien mis à jour à chaque changement de données

feat: ajoute la possibilité d'indiquer la clé de ligne dans le tableau de données

---

.vitepress/config.ts
demo-app/App.vue
demo-app/components/AsyncButton.vue
demo-app/views/AppHome.vue
docs/composants.md
docs/guide/ecosysteme.md
package.json
pnpm-lock.yaml
src/components/DsfrHeader/DsfrHeader.md
src/components/DsfrHeader/DsfrHeader.stories.ts
src/components/DsfrHeader/DsfrHeader.types.ts
src/components/DsfrHeader/DsfrHeader.vue
src/components/DsfrRadioButton/DsfrRadioButton.types.ts
src/components/DsfrSearchBar/DsfrSearchBar.md
src/components/DsfrSearchBar/DsfrSearchBar.vue
src/components/DsfrSearchBar/docs-demo/DsfrSearchBarDemo.vue
src/components/DsfrSegmented/DsfrSegmented.md
src/icons.ts
src/stories/docs/01-intro.stories.mdx

- **fix(DsfrHeader): 🐛 permet un id pour searchbar**
- **docs: 📝 corrections de liens**
- **fix(demo-app): 🐛 Met la navigation dans le slot prévu du header**

767 mettre un id sur dsfrsearchbar dans dsfrheader

---

src/components/DsfrModal/DsfrModal.stories.ts
src/components/DsfrModal/DsfrModal.types.ts
src/components/DsfrModal/DsfrModal.vue

feat(DsfrModal): ✨ ajout label bouton fermeture

---

.vitepress/config.ts
demo-app/App.vue
demo-app/router.js
demo-app/views/AppTags.vue
demo-app/views/CardTile.vue
docs/composants.md
docs/gabarit-doc-composant.md
package.json
pnpm-lock.yaml
src/components/DsfrCard/docs-demo/DsfrCardDemo.vue
src/components/DsfrCard/docs-demo/DsfrCardDemoActions.vue
src/components/DsfrFooter/DsfrFooter.stories.ts
src/components/DsfrRadioButton/DsfrRadioButton.spec.ts
src/components/DsfrRadioButton/DsfrRadioButton.stories.ts
src/components/DsfrTag/DsfrTag.md
src/components/DsfrTag/DsfrTag.vue
src/components/DsfrTile/DsfrTile.md
src/components/DsfrTile/DsfrTile.stories.ts
src/components/DsfrTile/DsfrTile.vue
src/components/DsfrTile/DsfrTiles.stories.ts
src/components/DsfrTile/DsfrTiles.types.ts
src/components/DsfrTile/docs-demo/DsfrTileDemo.vue

- permet d’utiliser la première zone de détails (pour tag ou badges)
- permet d’utiliser facilement un *artwork* du dsfr
- améliore la documentation

feat(DsfrTile): ✨ améliore DsfrTile

---

src/components/DsfrCallout/DsfrCallout.vue
src/components/DsfrModal/DsfrModal.vue
src/components/DsfrNavigation/DsfrNavigationMenuLink.vue

- DsfrModal
- DsfrCallout
- DsfrNavigationMenuLink

fix: 🐛 check if icon is not nullish

---

src/components/DsfrCallout/DsfrCallout.stories.ts
src/components/DsfrCallout/DsfrCallout.types.ts
src/components/DsfrCallout/DsfrCallout.vue

- DsfrCallout
Sur le DSFR, le titre de la mise en avant est optionnel
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/mise-en-avant

fix: callout title is optional

---

demo-app/App.vue
src/components/DsfrFooter/DsfrFooter.vue

fix(DsfrFooter): 🐛 correction logo opérateur et hyperlien

---

demo-app/App.vue
src/components/DsfrFooter/DsfrFooter.md
src/components/DsfrFooter/DsfrFooter.stories.ts
src/components/DsfrFooter/DsfrFooter.vue

fix(DsfrFooter): 🐛 retrait style imposé

---

src/components/DsfrTile/DsfrTile.vue
src/components/DsfrTile/DsfrTiles.types.ts

prend en compte la classe enlarge-button

feat: :sparkles: Maj 1.12.0 le composant tuile

---

src/components/DsfrNotice/DsfrNotice.md
src/components/DsfrNotice/DsfrNotice.spec.ts
src/components/DsfrNotice/DsfrNotice.stories.ts
src/components/DsfrNotice/DsfrNotice.types.ts
src/components/DsfrNotice/DsfrNotice.vue
src/components/DsfrNotice/docs-demo/DsfrNoticeExample.vue

Il y a un problème avec les tests cypress, qui ne passent pas parce qu'il y a une erreur lié à ce commit  , https://github.com/GouvernementFR/dsfr/commit/71d21990b615d23fb5ca30d81caaf58b6c8e4ff3
le hack 0/0 ne passe pas j'ai l'impression
ça casse aussi le build pour le coup
https://github.com/dnum-mi/vue-dsfr/issues/851

feat: ✨ Mettre à jour DsfrNotice avec l'udpate du Dsfr en 1.12

---

src/components/DsfrCheckbox/DsfrCheckbox.types.ts
src/components/DsfrCheckbox/DsfrCheckboxSet.vue
src/components/DsfrRadioButton/DsfrRadioButton.types.ts
src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
src/components/DsfrSelect/DsfrSelect.vue

Ajout attribut aria-invalid pour les éléments de formulaire qui ne pouvaient pas le récupérer

fix: :bug: Ajout attribut aria-invalid

---

src/components/DsfrCard/DsfrCard.md
src/components/DsfrCard/DsfrCard.spec.ts
src/components/DsfrCard/DsfrCard.types.ts
src/components/DsfrCard/DsfrCard.vue
src/components/DsfrCard/docs-demo/DsfrCardDemo.vue

https://github.com/dnum-mi/vue-dsfr/issues/909

feat(DsfrCard): ✨ permet d’ajouter des badges dans le header

---

src/components/DsfrCard/DsfrCard.md

Oublie dans https://github.com/dnum-mi/vue-dsfr/pull/913 d'update la doc avec la nouvelle props

docs(DsfrCard): 📝 mise à jour de la doc des propds de dsfrCard

---

src/components/DsfrHeader/DsfrHeader.stories.ts
src/components/DsfrHeader/DsfrHeader.vue

fix(DsfrHeader): lien homeTo même sans serviceTitle

---

src/components/DsfrHeader/DsfrHeader.types.ts
src/components/DsfrHeader/DsfrHeaderMenuLink.vue

- pour cohérence avec DsfrNavigationMenuLink qui peuvent être intégrés à l’en-tête

fix(DsfrHeaderMenuLink): 🐛 déprécie href

---

demo-app/App.vue
src/components/DsfrHeader/DsfrHeader.types.ts
src/components/DsfrHeader/DsfrHeader.vue
src/components/DsfrHeader/docs-demo/DsfrHeaderDemo.vue

fix(DsfrHeader): 🐛 bordure en haut de navigation principale

---

src/components/DsfrRadioButton/DsfrRadioButtonSet.vue

fix(DsfrRadioButtonSet): corrige la position du message

---

.vitepress/config.ts
src/components/DsfrHighlight/DsfrHighlight.md
src/components/DsfrHighlight/DsfrHighlight.stories.ts
src/components/DsfrHighlight/DsfrHighlight.types.ts
src/components/DsfrHighlight/DsfrHighlight.vue
src/components/DsfrHighlight/docs-demo/DsfrHighlightDemo.vue

permet d’utiliser la prop color pour la couleur de la bordure

feat(DsfrHighlight): ✨ ajoute la prop color

---

docs/composants.md
src/components/DsfrDataTable/DsfrDataTable.vue

fix https://github.com/dnum-mi/vue-dsfr/issues/950

fix(DsfrDataTable): 🐛 fix selection with selectAll

---

meta/custom-icon-collections-creator.js

ça va créer des lignes dans ce style, une par collection
```ts
export const ri = { accountCircleLine: 'ri:account-circle-line', addLine: 'ri:add-line', ... } as const
```
qui permettra au dev d'appeler les icones dans son code en se basant sur `icon-collections.ts`

feat: :sparkles: make icon dictionnary

---

src/components/DsfrPagination/DsfrPagination.vue

Proposition de correction du #1054

fix(pagination): 🐛 retire la notion de disabled sur les tags a

---

src/components/DsfrDataTable/DsfrDataTable.vue
src/components/DsfrPagination/DsfrPagination.types.ts
src/components/DsfrPagination/DsfrPagination.vue

fix: 🐛 Ajout d’unicité sur les IDs d’un composant DataTable

---

src/components/DsfrTabs/DsfrTabItem.vue

J'avais besoin de ce binding pour ajouter disabled sur les onglets

feat(DsfrTabs):  ajoute un binding pour les onglets

---

src/components/DsfrFooter/DsfrFooterPartners.md
src/components/DsfrFooter/DsfrFooterPartners.vue

feat: add title tag props for footer partners

---

src/components/DsfrFooter/DsfrFooter.vue

Ajoute l'intitulé visible des liens du footer à leur alternative accessible
