- package.json
Le paquet n'est pas privé et ne peut pas être déployé avec Github package s'il est privé
> chore: :wrench: Supprime l'état "privé" du package

- src/index.js
Le CSS doit être importé à part comme décrit dans la
[documentation](https://vue-dsfr.netlify.app/?path=/story/docs-guide-d-utilisation--page#comment-d%C3%A9buter).
> fix: :bug: Le CSS doit être importé à part

- src/components/DsfrTabs/DsfrTabs.vue
Pour pouvoir gérer de façon personnalisée le contenu des onglets
> feat: :sparkles: Emét l'évenement 'select-tab' lors du clic sur TabItem

- src/stories/composables/composables.stories.mdx
Ajoute un lien vers un Stackblitz avec utilisation complète du composable Stackblitz
> docs: :memo: Ajoute lien vers exemple useScheme

- src/components/DsfrInput/DsfrInput.vue
Pour être en cohérence avec le DsfrSelect, ajout de * au label si le champ est obligatoire
Fix: #221
> fix: :bug: Ajout de * si le champs est requis

- src/components/DsfrNavigation/DsfrNavigationMenu.vue
Transmid toggle-id event to parent so that the menu can be closed when navigate
Fix: #219
> fix([DsfrNavigationMenu]): :bug: Transmit toggle-id event to parent

- package.json
- rollup.config.js
- src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
- src/components/DsfrCard/DsfrCard.vue
- src/components/DsfrConsent/DsfrConsent.vue
- src/components/DsfrFooter/DsfrFooter.vue
- src/components/DsfrFooter/DsfrFooterLinkList.vue
- src/components/DsfrHeader/DsfrHeader.stories.js
- src/components/DsfrHeader/DsfrHeader.vue
- src/components/DsfrHeader/DsfrHeaderMenuLink.vue
- src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
- src/components/DsfrSideMenu/DsfrSideMenuLink.stories.js
- src/components/DsfrSideMenu/DsfrSideMenuLink.vue
- src/components/DsfrSideMenu/DsfrSideMenuList.stories.js
- src/components/DsfrSideMenu/DsfrSideMenuList.vue
- src/components/DsfrTag/DsfrTag.vue
- src/components/DsfrTile/DsfrTile.vue
- types/components/DsfrCard/DsfrCard.vue.d.ts
- types/components/DsfrConsent/DsfrConsent.vue.d.ts
- types/components/DsfrFooter/DsfrFooter.vue.d.ts
- types/components/DsfrFooter/DsfrFooterLinkList.vue.d.ts
- types/components/DsfrHeader/DsfrHeader.vue.d.ts
- types/components/DsfrHeader/DsfrHeaderMenuLink.vue.d.ts
- types/components/DsfrNavigation/DsfrNavigationMenuLink.vue.d.ts
- types/components/DsfrSideMenu/DsfrSideMenuLink.vue.d.ts
- types/components/DsfrSideMenu/DsfrSideMenuList.vue.d.ts
- types/components/DsfrTag/DsfrTag.vue.d.ts
- types/components/DsfrTile/DsfrTile.vue.d.ts
L’utilisation de nuxt-link ne fonctionnant pas, utilise toujours
router-link, comme la bibliothèque vuestic-ui
> fix: :bug: Utilise toujours router-link pour les liens internes

- src/components/DsfrAccordion/DsfrAccordion.e2e.js
- src/components/DsfrFollow/DsfrFollow.e2e.js
- src/components/DsfrFollow/DsfrSocialNetworks.vue
- src/components/DsfrFooter/DsfrFooter.vue
- src/components/DsfrFranceConnect/DsfrFranceConnect.vue
- src/components/DsfrHeader/DsfrHeader.e2e.js
- src/components/DsfrHighlight/DsfrHighlight.e2e.js
- src/components/DsfrInput/DsfrInput.e2e.js
- src/components/DsfrLogo/DsfrLogo.e2e.js
- src/components/DsfrMedia/DsfrMedia.e2e.js
- src/components/DsfrPagination/DsfrPagination.e2e.js
- src/components/DsfrQuote/DsfrQuote.vue
- src/components/DsfrSearchBar/DsfrSearchBar.vue
- src/components/DsfrShare/DsfrShare.spec.js
- src/components/DsfrShare/DsfrShare.vue
- src/components/DsfrTabs/DsfrTabs.e2e.js
- fix: :bug: Ajoute l'attribut rel="noopener noreferrer" aux balises <a> contenant un attribut "target"
- style: :art: Corrige les warnings remontées par le linter
#337
> Ajouter l'attribut `rel` avec la valeur `noreferrer noopener` pour les balises `<a>` qui ont un attribut `target`

- src/components/DsfrNavigation/DsfrNavigation.vue
Se met en écoute du clic et vérifie si l'élément cliqué est à l'intérieur ou à l'extérieur du menu
Fix: #426 
Fix: #427
> fix(DsfrNavigation): :bug: Fermeture du menu si clic à l'extérieur et si touche Echap pressée

- src/components/DsfrCard/DsfrCard.vue
Les styles du DSFR ont changé, le modificateur `--no-arrow` n’existe plus
> fix: :bug: Ne pas afficher de flèche si noArrow = true

- src/components/DsfrButton/DsfrButton.stories.js
- src/components/DsfrButton/DsfrButton.vue
- src/components/DsfrButton/DsfrButtonGroup.spec.js
- src/components/DsfrButton/DsfrButtonGroup.stories.js
- src/components/DsfrButton/DsfrButtonGroup.vue
Corrige le comportement des Groupes de Bouton:
Il y avait une inconpréhension entre les classes pour définir la taille des boutons et les classes pour passer en `inline` à des breakpoints définis:
- La taille n'était pas définie sur les boutons
- La taille n'était pas definie sur le groupe avec les classes `fr-btns-group--sm|md|lg`
- Le comportement `inline` n'était pas correct, j'ai déprécié la prop `inline` pour utiliser `inlineLayoutWhen` qui permet de choisir entre `never|always|small|medium|large`. Ce qui correspond aux classes `fr-btns-group--inline` ou bien `fr-btns-group--inline-sm|md|lg`
- Il manquait le style bouton `tertiary-no-outline`
BREAKING CHANGE: Button group `inline` prop is deprecated in favor of `inlineLayoutWhen`
> fix(DsfrButtonGroup): Button group does not respect `sizes` and `inlineLayoutWhen` rules

- src/components/DsfrQuote/DsfrQuote.stories.js
- src/components/DsfrQuote/DsfrQuote.vue
Exemple: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/citation
Cela permet de retirer l'image si la props n'est pas définie, et éviter d'avoir un placeholder qui glitch
> fix(DsfrQuote): DsfrQuote should be usable without image

- src/components/DsfrFooter/DsfrFooter.stories.js
- src/components/DsfrFooter/DsfrFooter.vue
- L'icone external est déjà gérée en CSS, pas besoin de l'ajouter à la main
- Les props `licence*` n'etaient pas bindées dans Storybook
- Retirer le target `_blank` si la page de license est interne
> fix(DsfrFooter): Removed useless VIcon on licence link, bind Storybook props

- src/components/DsfrFieldset/DsfrFieldset.spec.js
- src/components/DsfrFieldset/DsfrFieldset.stories.js
- src/components/DsfrFieldset/DsfrFieldset.vue
- Actuellement
- Devrait ressembler à 
Exemple d'intégration: https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles-et-blocs-fonctionnels/modele-de-page-de-creation-de-compte
> fix(DsfrFieldset): Missing `fr-fieldset__element` elements to wrap Fieldset hint and content

- src/components/DsfrAccordion/DsfrAccordion.stories.js
- src/components/DsfrAccordion/DsfrAccordion.vue
- src/utils/random-utils.js
- On ne pouvait pas fermer un accordion
- J'ai essayé de porter [le code JS du DSFR](https://github.com/GouvernementFR/dsfr/blob/main/src/core/script/collapse/collapse.js#L61) pour setter les variables CSS pendant l'animation des accordions 
- Il manquait un AccordionGroup dans l'exemple Storybook, ça ajoutait une marge
> fix: Fixed and improved Accordions

- src/components/DsfrPagination/DsfrPagination.vue
> [DsfrPagination] Audit RGAA : La page courante ne doit pas porter l'attribut `disabled`

- src/components/DsfrHeader/DsfrHeaderMenuLink.spec.js
- src/components/DsfrHeader/DsfrHeaderMenuLink.vue
Closes #511 => permettre d'avoir un lien de type `mailto` dans les `quickLinks` d'un `DsfrHeader`
> feat: :sparkles: allow mailto links in DsfrHeaderMenuLink

- src/components/DsfrNavigation/DsfrNavigationMenuLink.spec.js
- src/components/DsfrNavigation/DsfrNavigationMenuLink.stories.js
- src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
Comme échanger sur #498 voici ma proposition de PR
J'ai pas mal galéré ... car il semblerait que les configurations js, ts et surtout vitest ne supportent pas windows OS sur ce projet.
😄  Je fais parti des rares adeptes de cet OS...
J'ai pris des erreur d'import sur les tests utilisant `@/../../` par exemple `Error: Failed to load url E:/E:/vue-dsfr/tests/unit/test-utils.js` 
Mais bon, j'ai réussi à faire tourner les tests du DsfrNavigationMenuLink donc voici ma proposition pour ajouter une icône facultative.
Ps: pourquoi utiliser [testing-library](https://testing-library.com/) au lieu de [vue-test-utils](https://test-utils.vuejs.org/guide/) ? Je suis curieux ^^
> feat: ✨ Ajoute l'icône optionnelle au DsfrNavigationMenuLink

- src/components/DsfrPagination/DsfrPagination.vue
https://react-dsfr-components.etalab.studio/?path=/docs/components-pagination--default
Pagination should display prev and next labels. They're auto hidden in SM breakpoint.
> fix(DsfrPagination): Missing prev and next page links text

- src/components/DsfrAccordion/DsfrAccordion.spec.js
- src/components/DsfrAccordion/DsfrAccordion.stories.js
- src/components/DsfrAccordion/DsfrAccordion.vue
- src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
- src/components/DsfrLanguageSelector/DsfrLanguageSelector.vue
- src/components/DsfrNavigation/DsfrNavigation.spec.js
- src/components/DsfrNavigation/DsfrNavigation.vue
- src/components/DsfrNavigation/DsfrNavigationMegaMenu.vue
- src/components/DsfrNavigation/DsfrNavigationMenu.vue
- src/components/DsfrSideMenu/DsfrSideMenu.stories.js
- src/components/DsfrSideMenu/DsfrSideMenu.vue
- src/components/DsfrSideMenu/DsfrSideMenuList.vue
- src/components/DsfrTabs/DsfrTabs.stories.ts
- src/components/DsfrTabs/DsfrTabs.vue
- src/components/DsfrTranscription/DsfrTranscription.stories.js
- src/components/DsfrTranscription/DsfrTranscription.vue
- src/composables.js
- types/components/DsfrTranscription/DsfrTranscription.vue.d.ts
I've created an example in which collapsable animation does not perform well.
- Single accordion perform pretty well
- Nested accordion sort of well-ish
- SideMenu does not animate at all
- Accordion in SideMenu animation is bouncy
I'll try to implement vanilla DSFR JS code to these components using `@transitionend` to reset CSS vars.
I don't know how to get super smooth CSS anims like on React DSFR https://react-dsfr-components.etalab.studio/?path=/docs/components-sidemenu--side-menu-with-2-levels
> fix: Fix collapsable behaviour using a new composable

- src/components/DsfrSelect/DsfrSelect.vue
Dans la version TS du DsfrSelect, il y a une coquille dans la définition des propriétés. Ainsi le message d'erreur ou de succès ne sont pas injectables par le composant parent.
Exemple :
```ts
<DsfrSelect
ref="agentCategorySelect"
label="Catégorie"
:model-value="modelValue"
:required="required"
:options="categories"
:error-message="errorMessage"
@update:model-value="(value:string) => $emit('update:model-value', value)"
/>
```
Ce faisant, les propriétés finissent dans $attrs, exemple:
Définir les propriétés dans le defineProps pour être aligné avec les defaultValue fournies
> chore: 🏷️ fix props for DsfrSelect

- src/components/DsfrSelect/DsfrSelect.stories.ts
- src/components/DsfrSelect/DsfrSelect.vue
permet de personnaliser le texte de l’option sélectionnée par défaut si aucune option valide n’est sélectionnée
> feat(DsfrSelect): :sparkles: permet personnalisation de texte

- src/components/DsfrTile/DsfrTile.spec.ts
- src/components/DsfrTile/DsfrTile.stories.ts
- src/components/DsfrTile/DsfrTile.vue
- src/components/DsfrTile/DsfrTiles.spec.ts
Le DSFR a apporté des changements au composant Tuile, cette PR a pour but de s'aligner sur leur dernière version
> feat: :sparkles: Mise à jour du composant Tuile

- .eslintrc.js
- src/components/DsfrCard/DsfrCard.stories.ts
- src/components/DsfrCard/DsfrCard.vue
Le DSFR a apporté une nouvelle propriété au composant Card, cette PR a pour but de s'aligner sur leur dernière version
> feat: :sparkles: Mise à jour du composant Carte

- src/components/DsfrHeader/DsfrHeader.stories.ts
- src/components/DsfrHeader/DsfrHeader.vue
Sauf erreur de ma part, le slot par défaut du composant DsfrHeader ne permet pas d'obtenir le comportement prévu pour le menu de nav primaire.
En dessous de LG, le menu de nav reste sous le header :
En dessous de LG, quand la modale est fermée, le menu est invisible :
En dessous de LG, quand la modale est ouverte, le menu de nav se loge sous les quicklinks :
Après quelque tâtonnements, j'ai l'impression qu'un slot nommé et présent deux fois dans le composant DsfrHeader est la meilleure façon d'obtenir cet effet. Je ne sais pas si il y a des contre indications à faire ça. J'ai laissé le slot par défaut dans le commit pour retrocompatibilité.
Pour fermer la modale depuis le composant passé dans le slot (par exemple lorsqu'on change de route via le menu de navigation), on peut passer le …
> feat: ✨ nouveau slot nommé dans le composant DsfrHeader pour le menu de nav primaire

- src/components/DsfrModal/DsfrModal.vue
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/modale/
> fix: 🐛 Les boutons de la modale deviennent inline seulement pour les écrans en dessous de lg

- src/components/DsfrTile/DsfrTile.spec.ts
- src/components/DsfrTile/DsfrTile.stories.ts
- src/components/DsfrTile/DsfrTile.vue
- src/components/DsfrTile/DsfrTiles.spec.ts
[BREAKING CHANGE:](https://www.conventionalcommits.org/en/v1.0.0/) les props 'verticalAtMd' et 'verticalAtLg' n'existent plus (utiliser `vertical="md"` ou `vertical="lg"`)
> feat: :sparkles: Nouvelle implémentation du composant DsfrTile

- src/components/DsfrFooter/DsfrFooter.vue
Le lien du logo opérateur était présent même en l'absence de logo, un retour RGAA nous a demandé de le supprimer, j'ai donc hissé le v-if au niveau du lien afin de conserver le même fonctionnement sans que l'accessibilité du composant n'en pâtisse.
> fix: :bug: Hisse le v-if au niveau du lien du logo operateur

- src/components/DsfrModal/DsfrModal.stories.ts
- src/components/DsfrModal/DsfrModal.vue
> feat(DsfrModal): ✨ changer la taille de la modale

- package.json
Le package est maintenant configuré en ESM, l’extension .js est donc utilisée pour le build en ESM, et plus .mjs
> fix: :wrench: corrige l’extension

- src/composables/useTabs.stories.mdx
le lien généré n'était pas fonctionnel: https://vue-dsfr.netlify.app/?path=/?path=/docs/composants-dsfrtabs--docs
Lien attendu: https://vue-dsfr.netlify.app/?path=/docs/composants-dsfrtabs--docs
> fix(docs): correction référence DsfrTabs dans useTabs

- docs/pour-commencer.md
- src/index.ts
- src/meta/autoimport-preset.ts
- src/meta/component-resolver.ts
- src/meta/index.ts
- src/meta/ovi-autoimport-preset.ts
- l’autoimport est utilisable dans Vite et dans nuxt (pour les composables)
- le component resolver est utilisable dans Vite
> feat: :sparkles: ajoute un preset autoimport et un resolver

- src/components/DsfrFooter/DsfrFooter.spec.ts
- src/components/DsfrFooter/DsfrFooter.types.ts
- src/components/DsfrFooter/DsfrFooter.vue
Il est [parfois nécessaire d'inclure des liens externes](https://github.com/ecolabdata/ecospheres-front/pull/247) dans les liens obligatoires du footer. 
Cette proposition ajoute le support de ces liens externes, de manière similaire à ce qui est fait dans `DsfrFooterLinkList`, pour les props `beforeMandatoryLinks`, `mandatoryLinks` and `afterMandatoryLinks`.
> feat: support external links in footer *mandatoryLinks

- .vitepress/config.ts
- .vitepress/theme/style.css
- docs/docs-demo/DemoIconesDansComposants.vue
- docs/ecosysteme.md
- docs/guide/index.md
- docs/icones.md
- docs/index.md
**Pour information**, il s'agit d'une première étape de la migration des éléments de StoryBook vers VitePress.
Deux options s'ouvrent à cette migration :
- Cette branche fait office référence avant une intégration finale ;
- Cette branche sera fusionnée en `develop` et d'autres apporteront des modifications supplémentaires par la suite.
**Vérifications à effectuer**
- Les liens **externes** de navigation et de la [page d'introduction](http://localhost:5173/guide/) doivent être fonctionnels ;
- [TODO] Les liens **internes** de navigation et de la [page d'introduction](http://localhost:5173/guide/) doivent rediriger vers une page vitepress ;
- Le lien Discord est fonctionnel.
> docs(vitepress): 📝 Migration de Storybook vers VitePress

- src/components/DsfrButton/DsfrButton.vue
- src/components/DsfrButton/DsfrButtonGroup.vue
- src/components/DsfrCallout/DsfrCallout.types.ts
- src/components/DsfrCallout/DsfrCallout.vue
- src/components/DsfrFieldset/DsfrFieldset.vue
- src/components/DsfrHeader/DsfrHeader.vue
- src/components/DsfrHeader/DsfrHeaderMenuLink.vue
- src/components/DsfrInput/DsfrInputGroup.vue
- src/components/DsfrModal/DsfrModal.vue
- src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
- src/components/DsfrTable/DsfrTable.types.ts
- src/components/DsfrTable/DsfrTableHeader.vue
- src/components/DsfrTag/DsfrTag.vue
- src/components/DsfrTooltip/DsfrTooltip.vue
Désormais tous les composants qui ont une prop `icon` peuvent recevoir en valeur
le nom d’une classe correspondant à une icône DSFR.
> feat: :sparkles: permet d’utiliser les icônes DSFR

- src/components/DsfrFooter/DsfrFooter.spec.ts
- src/components/DsfrFooter/DsfrFooter.vue
Désormais il faut que la prop licenceText ne soit pas falsy (chaîne vide) pour que le texte de la licence s’affiche
> fix: :bug: ajoute condition pour affichage div.fr-footer__bottom-copy

- src/components/DsfrTable/DsfrTable.types.ts
- src/components/DsfrTable/DsfrTable.vue
feat: Introduction de la fonctionnalité améliorée de clé de ligne dans le tableau de données
Cette demande d'extraction traite d'une amélioration cruciale de la fonctionnalité du tableau de données en introduisant la possibilité de définir une clé de ligne personnalisée. La mise en œuvre actuelle, où table-row dépend de l'index de la boucle, s'est avérée inexacte lors de la mise à jour du tableau avec de nouvelles données.
- Ajout de l'attribut `row-key` au composant `<DsfrTable>`.
- Les utilisateurs peuvent désormais spécifier la clé de ligne souhaitée, améliorant la capacité du tableau à se mettre à jour ou à se réafficher correctement.
```html
<DsfrTable
:title="title"
:headers="['applicationid', 'longname', 'comments', 'createdat']"
row-key="applicationid"
:rows="rows"
/>
```
```html …
```
> feat: Introduction de la fonctionnalité améliorée de clé de ligne dans le tableau de données

- package-lock.json
- src/components/DsfrTable/DsfrTable.types.ts
- src/components/DsfrTable/DsfrTable.vue
Je crée une `DsfrTable` en lui passant une props `rows` issue de ma fonction `getRows`, typée comme ci-dessous :
```js
const getRows: (arrArg: ArgType[]) => {
component: string;
text: string;
title: string;
class: string;
onClick: () => any;
}[][]
```
TS m'indique une erreur de typage sur la props `rows` : 
```js
Type '{ component: string; text: string; title: string; class: string; onClick: () => any; }[][]' is not assignable to type '(string[] | DsfrTableRowProps)[]'.ts(2322)
DsfrTable.vue.d.ts(23, 5): The expected type comes from property 'rows' which is declared here on type 'Partial<{ currentPage: number; headers: DsfrTableHeadersProps; rows: (string[] | DsfrTableRowProps)[]; rowKey: string | [...] 
```
> fix: :label: accept array of DsfrTableCellProps in DsfrTableRowsProps

- src/components/DsfrRadioButton/DsfrRadioButton.types.ts
Désormais, modelValue peut prendre la valeur undefined dans
la prop modelValue de DsfrRadioButtonSet.
> fix(DsfrRadioButtonSet): 🐛 modelValue undefined

- .vitepress/config.ts
- demo-app/App.vue
- docs/composants.md
- docs/guide/ecosysteme.md
- src/components/DsfrHeader/DsfrHeader.stories.ts
- src/components/DsfrSegmented/DsfrSegmented.md
- src/stories/docs/01-intro.stories.mdx
Des corrections de liens présents dans la documentation et le site de démo : 
- ajout de www. devant systeme-de-design.gouv.fr (évite un message de certificat invalide)
- certains liens vers le storybook pointaient vers le nouveau site de la documentation
Je vois qu'il y a deux adresses pour le storybook : https://storybook.vue-ds.fr et https://stories.vue-ds.fr.  
Je n'ai pas vu s'il y a une différence ou si le contenu est le même, ce n'est peut-être pas utile d'avoir les deux (la 1ère a plus d'occurrences dans les sources du projet).
> docs: 📝 corrections de liens

- demo-app/App.vue
Bonjour,
Petite proposition de correction sur la démo pour corriger l'affichage de la navigation en responsive (et mettre en avant une bonne utilisation des composants).
> fix(demo-app): 🐛 Met la navigation dans le slot prévu du header

- .vitepress/config.ts
- src/components/DsfrButton/DsfrButton.md
- src/components/DsfrCard/DsfrCard.md
- src/components/DsfrCard/DsfrCard.types.ts
- src/components/DsfrCard/DsfrCard.vue
L’icône de détail est maintenant implémentée au début et à la fin
dans le composant DsfrCard.
> fix(DsfrCard): 🐛 implémente detailIcon

- docs/gabarit-doc-composant.md
- src/components/DsfrRadioButton/DsfrRadioButton.types.ts
- src/components/DsfrRadioButton/DsfrRadioButton.vue
- src/components/DsfrRadioButton/DsfrRadioButtonSet.spec.ts
- src/components/DsfrRadioButton/DsfrRadioButtonSet.stories.ts
- src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
- **fix(DsfrRadioButtonSet): 🐛 rend obligatoire la prop name**
- **chore: 📝 ajoute un gabarit pour doc de composant**
> Rendre obligatoire le paramètre `name` de DsfrRadioButtonSet

- demo-app/App.vue
- demo-app/router.js
- demo-app/views/AppTags.vue
- src/components/DsfrTag/DsfrTag.vue
- Corrige un avertissement console lors de l'utilisation d'un tag sans icône 
> Invalid prop: prop "name" is required.
- Ajoute une démo avec les composants tags
NB : j'ai du désactiver husky afin de pouvoir commiter et pusher, le linter et la suite de tests me renvoient respectivement les erreurs suivantes.
> Error: Failed to load plugin 'vue' declared in '.eslintrc.cjs': Cannot find module './_baseSortedIndex'
> Serialized Error: { code: 'MODULE_NOT_FOUND', requireStack: [ '/Users/alexandre/***/vue-dsfr/node_modules/lodash/isEqual.js' ] }
> fix(DsfrTag): corrige le tag sans icone et ajoute une démo

- src/components/DsfrHeader/DsfrHeader.vue
... car elle est déjà présente dans le composant DsfrHeaderMenuLinks
> fix: 🐛 supprime la balise nav de DsfrHeader

- demo-app/views/AppHome.vue
- src/components/DsfrTooltip/DsfrTooltip.vue
Prend en compte le parent pour la position du tooltip.
Si l’info-bulle est dans un élément relatif, sa position le prend en compte désormais.
> fix(DsfrTooltip): 🐛 prend en compte le parent

- src/components/DsfrRadioButton/DsfrRadioButton.md
- src/components/DsfrRadioButton/DsfrRadioButton.stories.ts
- src/components/DsfrRadioButton/DsfrRadioButton.types.ts
- src/components/DsfrRadioButton/DsfrRadioButton.vue
- src/components/DsfrRadioButton/DsfrRadioButtonSet.md
Related issue #832 
J'aurai aimé pouvoir faire un test / ajout dans la doc avec des SVG du DSFR mais je ne vois pas où les positionner pour éviter qu'il soit embarqué dans le package vue-dsfr.  
Ca vaudrait aussi le coup, d'avoir une doc mdx sur les artworks https://github.com/GouvernementFR/dsfr/tree/main/src/core/asset/artwork
> feat(DsfrRadioButton): ✨ ajout svg

- src/components/DsfrFooter/DsfrFooter.types.ts
- src/components/DsfrFooter/DsfrFooter.vue
> feat(DsfrFooter): ✨ gère l’attribut title des liens

- src/components/DsfrTooltip/DsfrTooltip.vue
Salut l’équipe vue-dsfr,
Je constate que si je veux ajouter un tooltip dans le header d’une data-table, lorsque je cliquerais sur le tooltip, je vais également déclencher le tri de ma colonne.
Le fix me semble être assez simple, il suffirait de rajouter un modificateur d’évènement sur le `@click` du composant
https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrTooltip/DsfrTooltip.vue#L127
Un `@click.stop` devrait faire l’affaire
Merci par avance et bonne journée :)
> fix(DsfrTooltip): 🐛 empêche la propagation du clic

- src/components/DsfrTooltip/DsfrTooltip.vue
- Affiche l’infobulle au focus du composant qui la contient
- Cache l’infobulle après l’appui sur la touche ESC (Échappe)
fix #952
> fix: 🐛 affiche l’infobulle au focus et la cache avec ESC

- src/components/DsfrHeader/DsfrHeader.vue
Salut la team vue-dsfr,
Il me semble qu’il y a une coquille en mobile sur ce composant, la balise `nav` est posée à la fois manuellement et à la fois par le composant `DsfrHeaderMenuLinks`.
Merci par avance et bonne journée :)
> fix: 🐛 double balise nav dans le DsfrHeader en mobile

- src/components/DsfrSelect/DsfrSelect.vue
Si il n'y a qu'une seule option et que le modelValue ne correspond pas, alors seulement l'option disponible est affichée mais il n'y a pas moyen de mettre à jour le choix et donc aucun emit.
> fix: :bug: blocked select when only one choice and not selected option

- demo-app/App.vue
- package.json
- src/components/DsfrNavigation/DsfrNavigation.vue
- src/components/DsfrNavigation/DsfrNavigationItem.spec.ts
Cette pull request introduit l'utilisation d'ID pour les éléments de navigation dans le composant  `DsfrNavigation` et met à jour la demo et les tests pertinents en conséquence.
* Passage de l'ID unique au composant `DsfrNavigationItem` dans `src/components/DsfrNavigation/DsfrNavigation.vue`.
* Ajout de l'importation de `useId` dans `demo-app/App.vue` pour générer des IDs uniques pour les éléments de navigation.
* Mise à jour de `navItems` dans `demo-app/App.vue` pour inclure des IDs uniques en utilisant `useId()`.
* Importation de `useId` dans `DsfrNavigationItem.spec.ts` pour générer des IDs uniques pour les tests.
* Mise à jour des cas de test dans `DsfrNavigationItem.spec.ts` pour vérifier la présence et la justesse de l'ID unique.
> feat(DsfrNavigation): :bug: ajoute de l'attribut `id` au composant `DsfrNavigationItem` depuis le composant `DsfrNavigation`

- src/components/DsfrSideMenu/DsfrSideMenu.types.ts
- src/components/DsfrSideMenu/DsfrSideMenu.vue
Hello (it's me again),
Autre composant qui nous remonte une [anomalie RGAA](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#8.9.1) et qui est présente sur le DSFR de base, le [Menu Latéral](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/menu-lateral).
Dans notre implémentation, la recommandation est de mettre un `<h2>`, mais je pense que de laisser la liberté au développeur de choisir son tag est plus pertinent.
Merci d'avance !
> fix: 🐛 DsfrSideMenu balise titre RGAA 8.9.1 NC

- src/components/DsfrAccordion/DsfrAccordion.vue
- src/composables/useCollapsable.ts
Bonsoir,
Suite à un bug remonté avec la mise à jour 7.2.0 sur un focus de lien à l'ouverture d'un accordéon et à [l'issue 999](https://github.com/dnum-mi/vue-dsfr/issues/999), je propose ce correctif.
Il permet de, au choix, ne pas focus le premier lien que le composant utilisant le composable `onTransitionEnd` pourrait posséder.
Dans le cas du `DsfrAccordion.vue`, il amène un comportement non désiré et provoque une anomalie en terme d'accessibilité en faisant ignorer du contenu par les lecteurs d'écran.
Une très bonne soirée
> fix: 🐛 DsfrAccordion shouldn't focus on toggle

- src/components/DsfrAccordion/DsfrAccordion.vue
- src/components/DsfrSideMenu/DsfrSideMenu.types.ts
- src/components/DsfrSideMenu/DsfrSideMenu.vue
- src/components/DsfrSideMenu/DsfrSideMenuList.vue
- src/composables/useCollapsable.ts
Cf. https://github.com/dnum-mi/vue-dsfr/issues/999
> fix: add capability to not auto focus for sidemenu

- docs/guide/pour-commencer.md
Bonjour,
S'agit-il bien d'un oubli ?
- Applique à pour-commencer.md la migration décrite dans migrations.md
> docs: 📝 corrige vite.config.ts suite à montée version 7.x -> 8.x

- src/components/DsfrRange/DsfrRange.vue
Hello l’équipe vue-dsfr,
Cette PR corrige les petites anomalies visuelles qu’on retrouvait sur le DsfrRange par rapport à la doc officielle
C’est probablement pas exactement iso à ce que fait le DSFR, mais ça s’en rapproche plus pour sur
> fix: 🐛 corrige les anomalies visuelles du dsfr-range

- src/components/DsfrTooltip/DsfrTooltip.vue
Aujourd'hui, le positonnement dynamique de l'infobulle ne prend pas en compte la largeur de celle-ci par rapport au bord droit de la fenêtre, mais utilise la largeur du bouton qui permet de l'afficher. Le problème d'overlapping n'est donc pas visible si le bouton est collé à la bordure droite, mais le devient avec un écart plus conséquent :
Aujourd'hui, le positionnement dynamique de l'infobulle ne prend pas en compte la hauteur de la fenêtre visible par l'utilisateur, mais la hauteur du document. Le problème d'overlapping n'est donc pas visible ci le document ne dépasse pas la fenêtre, mais le devient le cas échéant
En cas de redimensionnement de la fenêtre, il faut recalculer la position souhaitée de l'infobulle, qui peut éventuellement sortir de la fenêtre.
Nous pourrions utiliser un …
> Améliore le positionnement de l'infobulle (DsfrTooltip)

- src/components/DsfrRadioButton/DsfrRadioButton.types.ts
- src/components/DsfrRadioButton/DsfrRadioButton.vue
[Conformément au DSFR](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bouton-radio-riche), on devrait avoir la possibilité d’avoir des boutons radios riches sans utiliser de pictos
> fix: 🐛 ajoute la notion de rich sans icone pour les DsfrRadioButton

- src/components/DsfrHeader/DsfrHeader.vue
- [🐛 ajoute le timing de focus du bouton fermer des quickLinks en mode mobile](https://github.com/dnum-mi/vue-dsfr/commit/ae4808247e51dae8d2b73f396917403bbc292702)
Bug trouvé lors d'un audit RGAA sur le bouton burger menu du DsfrHeader.
Lorsque l'on ouvre le menu des `quickLinks`, le focus reste sur le bouton d'ouverture et ne va pas sur le premier élément interactif de la modal.
Il existe bien un [forçage du focus dans le composant](https://github.com/dnum-mi/vue-dsfr/blob/main/src/components/DsfrHeader/DsfrHeader.vue#L81), mais sans [`delay`](https://developer.mozilla.org/fr/docs/Web/API/Window/setTimeout#delay) du `setTimeout`, il s'execute au bon cycle de changement la première fois mais pas aux suivantes.
Etant donné que l'affichage de la `nav` se fait via un rendu conditionné …
> DsfrHeader fixes sur les boutons Menu et recherche

- src/components/VIcon/VIcon.vue
Fix #1037
Le composant `VIcon` provoque des warnings d'hydration mismatches.
Il semble qu'utiliser `v-bind()` et des styles en ligne (`style`) sur le même élément provoque une différence de rendu entre serveur et client.
Le problème a été relevé du côté de Vue, cf.  https://github.com/vuejs/core/issues/12439
On peut enlever le `v-bind()` et utiliser le `style` existant pour la `color`.
> fix(VIcon): avertissement de problème d'hydratation
